version: 2
updates:
  # npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '09:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
    groups:
      storybook:
        patterns:
          - '@storybook/*'
      vitest:
        patterns:
          - '@vitest/*'
          - 'vitest'
      postcss:
        patterns:
          - 'postcss*'
          - 'cssnano*'
          - 'autoprefixer'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '09:00'
      timezone: 'America/New_York'
    labels:
      - 'dependencies'
      - 'github-actions'
    groups:
      actions:
        patterns:
          - '*'
