/**
 * Icon IDs available in each sprite, organized by category.
 *
 * HDS icons:  src/assets/img/hds-icons/*.svg → hds-sprite.svg
 * USWDS icons: dist/assets/img/sprite.svg (from @uswds/uswds)
 *
 * To regenerate the HDS list:
 *   ls src/assets/img/hds-icons/*.svg | xargs -I{} basename {} .svg | sort
 *
 * To regenerate the USWDS list:
 *   grep -oP '(?<=id=")[^"]+' dist/assets/img/sprite.svg | sort
 *
 * When porting a USWDS icon to HDS, move it from uswdsUniqueIcons
 * to uswdsPortedIcons and add the new HDS name to the appropriate
 * HDS array.
 */

// ---------------------------------------------------------------------------
// HDS Icons (hds-sprite.svg)
// ---------------------------------------------------------------------------

/** UI icons — suitable for buttons, action bars, navigation. */
export const hdsUiIcons = [
  'archive',
  'arrow-chevron-down',
  'arrow-chevron-left',
  'arrow-chevron-right',
  'arrow-chevron-up',
  'arrow-circle-double-left',
  'arrow-circle-double-right',
  'arrow-circle-down',
  'arrow-circle-left',
  'arrow-circle-right',
  'arrow-circle-up',
  'arrow-filled-down',
  'arrow-filled-left',
  'arrow-filled-right',
  'arrow-filled-up',
  'arrow-line-diagonal',
  'arrow-line-down',
  'arrow-line-left',
  'arrow-line-right',
  'arrow-line-up',
  'asteroid',
  'calendar',
  'check',
  'check-circled',
  'close',
  'collapse',
  'comment',
  'download',
  'error',
  'expand',
  'facility',
  'file-archive',
  'file-audio',
  'file-code',
  'file-document',
  'file-generic',
  'file-image',
  'file-spreadsheet',
  'file-video',
  'filter',
  'gas-giant',
  'info',
  'list',
  'location',
  'map',
  'menu',
  'minus',
  'moon',
  'orbiter',
  'pause',
  'play',
  'plus',
  'print',
  'quote',
  'rotate',
  'rover',
  'rss',
  'search',
  'selection',
  'settings',
  'share',
  'slideshow',
  'sound-off',
  'sound-on',
  'subscribe',
  'terrestrial',
  'view-grid',
  'view-list',
  'view-mosaic',
  'view-single',
  'x-circled',
];

/** Logo/brand icons — third-party platform marks. */
export const hdsLogoIcons = ['logo-figma', 'logo-uswds'];

/** Tag/category icons — used in chips, filters, content type indicators. */
export const hdsTagIcons = [
  'tag-activity',
  'tag-all',
  'tag-article',
  'tag-bio',
  'tag-blog',
  'tag-data',
  'tag-encyclopedia',
  'tag-event',
  'tag-feature',
  'tag-file',
  'tag-gallery',
  'tag-image',
  'tag-infographic',
  'tag-interactive',
  'tag-landing',
  'tag-launch',
  'tag-media-advisory',
  'tag-movie',
  'tag-notification',
  'tag-podcast',
  'tag-press-release',
  'tag-previously-aired',
  'tag-slideshow',
  'tag-sound',
  'tag-status-update',
  'tag-subscribe',
  'tag-topic',
  'tag-video',
];

/** All HDS icons (UI + Tag + Logo combined). */
export const hdsIcons = [...hdsUiIcons, ...hdsTagIcons, ...hdsLogoIcons];

// ---------------------------------------------------------------------------
// USWDS Icons (sprite.svg)
// ---------------------------------------------------------------------------

/**
 * USWDS icons that have been ported to or replaced by an HDS icon.
 * Use the HDS version instead — these are kept here for reference
 * and for any stories that need to show the USWDS originals.
 *
 * USWDS name        → HDS equivalent
 * ─────────────────────────────────────
 * check             → check
 * close             → close
 * comment           → comment
 * error             → error
 * info              → info
 * list              → list
 * map               → map
 * menu              → menu
 * print             → print
 * search            → search
 * settings          → settings
 * share             → share
 */
export const uswdsPortedIcons = [
  'check',
  'close',
  'comment',
  'error',
  'info',
  'list',
  'map',
  'menu',
  'print',
  'search',
  'settings',
  'share',
];

/** USWDS icons with no HDS equivalent. */
export const uswdsUniqueIcons = [
  'accessibility_new',
  'accessible_forward',
  'account_balance',
  'account_box',
  'account_circle',
  'add',
  'add_circle',
  'add_circle_outline',
  'alarm',
  'alternate_email',
  'announcement',
  'api',
  'arrow_back',
  'arrow_downward',
  'arrow_drop_down',
  'arrow_drop_up',
  'arrow_forward',
  'arrow_upward',
  'assessment',
  'attach_file',
  'attach_money',
  'autorenew',
  'backpack',
  'bathtub',
  'bedding',
  'bookmark',
  'bug_report',
  'build',
  'calendar_today',
  'campaign',
  'camping',
  'cancel',
  'chat',
  'check_box_outline_blank',
  'check_circle',
  'check_circle_outline',
  'checkroom',
  'chevron_left',
  'chevron_right',
  'clean_hands',
  'closed_caption',
  'clothes',
  'cloud',
  'code',
  'connect_without_contact',
  'construction',
  'construction_worker',
  'contact_page',
  'content_copy',
  'coronavirus',
  'credit_card',
  'deck',
  'delete',
  'device_thermostat',
  'directions',
  'directions_bike',
  'directions_bus',
  'directions_car',
  'directions_walk',
  'do_not_disturb',
  'do_not_touch',
  'drag_handle',
  'eco',
  'edit',
  'electrical_services',
  'emoji_events',
  'error_outline',
  'event',
  'expand_less',
  'expand_more',
  'facebook',
  'fast_forward',
  'fast_rewind',
  'favorite',
  'favorite_border',
  'fax',
  'file_download',
  'file_present',
  'file_upload',
  'filter_alt',
  'filter_list',
  'fingerprint',
  'first_page',
  'flag',
  'flickr',
  'flight',
  'flooding',
  'folder',
  'folder_open',
  'format_quote',
  'format_size',
  'forum',
  'github',
  'grid_view',
  'group_add',
  'groups',
  'hearing',
  'help',
  'help_outline',
  'highlight_off',
  'history',
  'home',
  'hospital',
  'hotel',
  'hourglass_empty',
  'hurricane',
  'identification',
  'image',
  'info_outline',
  'insights',
  'instagram',
  'keyboard',
  'label',
  'language',
  'last_page',
  'launch',
  'lightbulb',
  'lightbulb_outline',
  'link',
  'link_off',
  'linkedin',
  'local_cafe',
  'local_fire_department',
  'local_gas_station',
  'local_grocery_store',
  'local_hospital',
  'local_laundry_service',
  'local_library',
  'local_offer',
  'local_parking',
  'local_pharmacy',
  'local_police',
  'local_taxi',
  'location_city',
  'location_on',
  'lock',
  'lock_open',
  'lock_outline',
  'login',
  'logout',
  'loop',
  'mail',
  'mail_outline',
  'masks',
  'medical_services',
  'military_tech',
  'more_horiz',
  'more_vert',
  'my_location',
  'navigate_before',
  'navigate_far_before',
  'navigate_far_next',
  'navigate_next',
  'near_me',
  'notifications',
  'notifications_active',
  'notifications_none',
  'notifications_off',
  'park',
  'people',
  'person',
  'pets',
  'phone',
  'photo_camera',
  'priority_high',
  'public',
  'push_pin',
  'radio_button_unchecked',
  'rain',
  'reduce_capacity',
  'remove',
  'remove_circle',
  'report',
  'restaurant',
  'rss_feed',
  'safety_divider',
  'sanitizer',
  'save_alt',
  'schedule',
  'school',
  'science',
  'security',
  'send',
  'sentiment_dissatisfied',
  'sentiment_neutral',
  'sentiment_satisfied',
  'sentiment_satisfied_alt',
  'sentiment_very_dissatisfied',
  'severe_weather',
  'shield',
  'shopping_basket',
  'snow',
  'soap',
  'social_distance',
  'sort_arrow',
  'spellcheck',
  'star',
  'star_half',
  'star_outline',
  'store',
  'support',
  'support_agent',
  'text_fields',
  'thumb_down_alt',
  'thumb_up_alt',
  'timer',
  'toggle_off',
  'toggle_on',
  'topic',
  'tornado',
  'translate',
  'trending_down',
  'trending_up',
  'twitter',
  'undo',
  'unfold_less',
  'unfold_more',
  'update',
  'upload_file',
  'verified',
  'verified_user',
  'visibility',
  'visibility_off',
  'volume_off',
  'warning',
  'wash',
  'wifi',
  'work',
  'x',
  'youtube',
  'zoom_in',
  'zoom_out',
  'zoom_out_map',
];

/** All USWDS icons (unique + ported combined). */
export const uswdsIcons = [...uswdsUniqueIcons, ...uswdsPortedIcons];
